### PR TITLE
[Feature/59] Add rules against arrow function feature

### PR DESCRIPTION
**Pull request by antonioeatgoat**
**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

**What kind of change does this PR introduce?**
Feature

**What is the current behavior?**
There is no rules against arrow function feature.

**What is the new behavior?**
Rules are being added

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by gmazzap** [comment]
> Question: Does this rule checks for the `static` keyword or another rule is responsible?

I added support tot is as well @TangRufus

**Review by gmazzap — APPROVED** [review]

**Comment by thefrosty** [comment]
Looks like this was the final PR into master which has since been deleted? I can open an issue if needed.

**Comment by gmazzap** [comment]
@thefrosty the branch `development` has been created off `feature/59` branch, which was the source of this PR.

And then, the `development` branch was used to created this PR: https://github.com/inpsyde/php-coding-standards/pull/69 which then has been merged into `version/2`.

So all the changes in this PR are already both in `version/2` and `development` branch.

For forward compatibility, if you plan to test the changes, please require the package via `^2@dev`, this will ensure you can not have any breakage in the case we rename/delete branches.

But please be aware that v2 is a work in progress for now, bugs are expected, and we would appreciate help in testing.

**Comment by thefrosty** [comment]
That's fine, I know previously there was some issues with v1 and maybe composer api v2,  so we discussed using `dev-master`. Since it was deleted that is no longer an option. Just wanted to call it out. Thanks.

**Pull request closed without merging**
